"""Curated RSS/Atom source list for the Mythara News Network.

Every URL below was verified live on 2026-09-27 by fetching it and
confirming it parses as RSS/Atom with items present. Dead or
bot-blocked feeds are documented, not silently included.

Spectrum: wire/international, US across the political spectrum,
independent outlets, Denver/local (Herb is in Denver), the TechTalk column
(tech & innovation feeds), and the Business column (IPO & markets feeds).
"""

from typing import Dict, List

# Each source: id, outlet label, political/cultural lean (labeled, not
# endorsed), beat, and the verified feed URL.
SOURCES: List[Dict[str, str]] = [
    # -- wire / international -------------------------------------------
    {"id": "bbc-world", "outlet": "BBC", "lean": "center",
     "beat": "international",
     "url": "http://feeds.bbci.co.uk/news/world/rss.xml"},
    {"id": "bbc-top", "outlet": "BBC", "lean": "center",
     "beat": "top stories",
     "url": "http://feeds.bbci.co.uk/news/rss.xml"},
    {"id": "aljazeera", "outlet": "Al Jazeera", "lean": "center-left / intl",
     "beat": "international",
     "url": "https://www.aljazeera.com/xml/rss/all.xml"},
    {"id": "france24", "outlet": "France 24", "lean": "center / intl",
     "beat": "international",
     "url": "https://www.france24.com/en/rss"},
    {"id": "cbc", "outlet": "CBC", "lean": "center / intl",
     "beat": "international",
     "url": "https://www.cbc.ca/cmlink/rss-topstories"},
    # -- US spectrum -----------------------------------------------------
    {"id": "npr", "outlet": "NPR", "lean": "center-left",
     "beat": "us news",
     "url": "https://feeds.npr.org/1001/rss.xml"},
    {"id": "cnn", "outlet": "CNN", "lean": "center-left",
     "beat": "us/world",
     "url": "http://rss.cnn.com/rss/edition.rss"},
    {"id": "nbc", "outlet": "NBC News", "lean": "center-left",
     "beat": "us news",
     "url": "https://feeds.nbcnews.com/nbcnews/public/news"},
    {"id": "abc", "outlet": "ABC News", "lean": "center",
     "beat": "us news",
     "url": "https://abcnews.go.com/abcnews/topstories"},
    {"id": "cbs", "outlet": "CBS News", "lean": "center",
     "beat": "us news",
     "url": "https://www.cbsnews.com/latest/rss/main"},
    {"id": "nyt", "outlet": "New York Times", "lean": "center-left",
     "beat": "us/world",
     "url": "https://rss.nytimes.com/services/xml/rss/nyt/World.xml"},
    {"id": "wapo", "outlet": "Washington Post", "lean": "center-left",
     "beat": "us/world",
     "url": "https://feeds.washingtonpost.com/rss/world"},
    {"id": "guardian", "outlet": "The Guardian", "lean": "center-left / intl",
     "beat": "international",
     "url": "https://www.theguardian.com/world/rss"},
    {"id": "bloomberg", "outlet": "Bloomberg", "lean": "center / business",
     "beat": "politics",
     "url": "https://feeds.bloomberg.com/politics/news.rss"},
    {"id": "wsj-world", "outlet": "Wall Street Journal", "lean": "center-right",
     "beat": "world/business",
     "url": "https://feeds.a.dj.com/rss/RSSWorldNews.xml"},
    {"id": "fox", "outlet": "Fox News", "lean": "right",
     "beat": "us news",
     "url": "http://feeds.foxnews.com/foxnews/latest"},
    # -- US right --------------------------------------------------------
    # Added 2026-10-04 per Herb: more Republican-side coverage.
    {"id": "nypost", "outlet": "New York Post", "lean": "right",
     "beat": "us news",
     "url": "https://nypost.com/feed/"},
    {"id": "washexaminer", "outlet": "Washington Examiner", "lean": "right",
     "beat": "us politics",
     "url": "https://www.washingtonexaminer.com/feed/"},
    {"id": "nationalreview", "outlet": "National Review", "lean": "right",
     "beat": "us politics",
     "url": "https://www.nationalreview.com/feed/"},
    {"id": "washingtontimes", "outlet": "Washington Times", "lean": "right",
     "beat": "us news",
     "url": "https://www.washingtontimes.com/rss/headlines/news/"},
    {"id": "dailycaller", "outlet": "Daily Caller", "lean": "right",
     "beat": "us politics",
     "url": "https://dailycaller.com/feed/"},
    {"id": "townhall", "outlet": "Townhall", "lean": "right",
     "beat": "us politics",
     "url": "https://townhall.com/feed/"},
    {"id": "breitbart", "outlet": "Breitbart", "lean": "right",
     "beat": "us politics",
     "url": "https://www.breitbart.com/feed/"},
    {"id": "axios", "outlet": "Axios", "lean": "center",
     "beat": "us news",
     "url": "https://www.axios.com/feeds/feed.rss"},
    {"id": "thehill", "outlet": "The Hill", "lean": "center",
     "beat": "us politics",
     "url": "https://thehill.com/feed/"},
    {"id": "pbs", "outlet": "PBS NewsHour", "lean": "center / public",
     "beat": "us/world",
     "url": "https://www.pbs.org/newshour/feeds/rss/headlines"},
    # -- independent -----------------------------------------------------
    {"id": "democracynow", "outlet": "Democracy Now!", "lean": "left / independent",
     "beat": "us/world",
     "url": "https://www.democracynow.org/democracynow.rss"},
    {"id": "intercept", "outlet": "The Intercept", "lean": "left / independent",
     "beat": "investigations",
     "url": "https://theintercept.com/feed/?lang=en"},
    {"id": "propublica", "outlet": "ProPublica", "lean": "nonprofit investigative",
     "beat": "investigations",
     "url": "https://www.propublica.org/feeds/propublica/main"},
    # -- military / defense ------------------------------------------------
    # Added 2026-10-04 per Herb: standing military coverage.
    {"id": "defensenews", "outlet": "Defense News", "lean": "defense trade",
     "beat": "military/defense",
     "url": "https://www.defensenews.com/arc/outboundfeeds/rss/?outputType=xml"},
    {"id": "militarytimes", "outlet": "Military Times", "lean": "military",
     "beat": "military",
     "url": "https://www.militarytimes.com/arc/outboundfeeds/rss/?outputType=xml"},
    {"id": "armytimes", "outlet": "Army Times", "lean": "military",
     "beat": "military/army",
     "url": "https://www.armytimes.com/arc/outboundfeeds/rss/?outputType=xml"},
    {"id": "navytimes", "outlet": "Navy Times", "lean": "military",
     "beat": "military/navy",
     "url": "https://www.navytimes.com/arc/outboundfeeds/rss/?outputType=xml"},
    {"id": "usni", "outlet": "USNI News", "lean": "naval / independent",
     "beat": "military/navy",
     "url": "https://news.usni.org/feed"},
    {"id": "thewarzone", "outlet": "The War Zone", "lean": "defense / tech",
     "beat": "military/tech",
     "url": "https://www.twz.com/feed"},
    {"id": "defensegov", "outlet": "U.S. Dept. of Defense", "lean": "official",
     "beat": "military/official",
     "url": "https://www.defense.gov/DesktopModules/ArticleCS/RSS.ashx?max=10&ContentType=1"},
    # -- topic feeds: standing coverage beats --------------------------------
    # Google News topic search — verified live 2026-09-27 (fetched, parsed,
    # ~100 items each). Item-level <source> names the real outlet; ingest.py
    # prefers it over this feed-level label.
    {"id": "gnews-trade", "outlet": "Google News", "lean": "aggregator / multi-outlet",
     "beat": "topic: us trade negotiations",
     "url": "https://news.google.com/rss/search?q=US%20trade%20negotiations&hl=en-US&gl=US&ceid=US:en"},
    {"id": "gnews-tariffs", "outlet": "Google News", "lean": "aggregator / multi-outlet",
     "beat": "topic: us tariffs & trade deals",
     "url": "https://news.google.com/rss/search?q=US%20tariffs%20trade%20deal&hl=en-US&gl=US&ceid=US:en"},
    # Added 2026-10-04: Republican-side + military topic coverage per Herb,
    # plus broader standing beats. Each aggregates hundreds of outlets.
    {"id": "gnews-gop", "outlet": "Google News", "lean": "aggregator / multi-outlet",
     "beat": "topic: republican party / GOP",
     "url": "https://news.google.com/rss/search?q=Republican%20Party%20GOP&hl=en-US&gl=US&ceid=US:en"},
    {"id": "gnews-congress-gop", "outlet": "Google News", "lean": "aggregator / multi-outlet",
     "beat": "topic: house republicans / senate GOP",
     "url": "https://news.google.com/rss/search?q=House%20Republicans%20Senate%20GOP&hl=en-US&gl=US&ceid=US:en"},
    {"id": "gnews-pentagon", "outlet": "Google News", "lean": "aggregator / multi-outlet",
     "beat": "topic: pentagon / US military",
     "url": "https://news.google.com/rss/search?q=Pentagon%20US%20military&hl=en-US&gl=US&ceid=US:en"},
    {"id": "gnews-veterans", "outlet": "Google News", "lean": "aggregator / multi-outlet",
     "beat": "topic: veterans / VA",
     "url": "https://news.google.com/rss/search?q=veterans%20VA&hl=en-US&gl=US&ceid=US:en"},
    {"id": "gnews-ai", "outlet": "Google News", "lean": "aggregator / multi-outlet",
     "beat": "topic: artificial intelligence",
     "url": "https://news.google.com/rss/search?q=artificial%20intelligence&hl=en-US&gl=US&ceid=US:en"},
    {"id": "gnews-cyber", "outlet": "Google News", "lean": "aggregator / multi-outlet",
     "beat": "topic: cybersecurity",
     "url": "https://news.google.com/rss/search?q=cybersecurity&hl=en-US&gl=US&ceid=US:en"},
    {"id": "gnews-scotus", "outlet": "Google News", "lean": "aggregator / multi-outlet",
     "beat": "topic: supreme court",
     "url": "https://news.google.com/rss/search?q=supreme%20court&hl=en-US&gl=US&ceid=US:en"},
    {"id": "gnews-immigration", "outlet": "Google News", "lean": "aggregator / multi-outlet",
     "beat": "topic: immigration",
     "url": "https://news.google.com/rss/search?q=immigration&hl=en-US&gl=US&ceid=US:en"},
    {"id": "gnews-economy", "outlet": "Google News", "lean": "aggregator / multi-outlet",
     "beat": "topic: US economy / inflation",
     "url": "https://news.google.com/rss/search?q=US%20economy%20inflation&hl=en-US&gl=US&ceid=US:en"},
    {"id": "gnews-climate", "outlet": "Google News", "lean": "aggregator / multi-outlet",
     "beat": "topic: climate change",
     "url": "https://news.google.com/rss/search?q=climate%20change&hl=en-US&gl=US&ceid=US:en"},
    {"id": "gnews-space", "outlet": "Google News", "lean": "aggregator / multi-outlet",
     "beat": "topic: space / NASA / SpaceX",
     "url": "https://news.google.com/rss/search?q=space%20NASA%20SpaceX&hl=en-US&gl=US&ceid=US:en"},
    {"id": "gnews-health", "outlet": "Google News", "lean": "aggregator / multi-outlet",
     "beat": "topic: public health",
     "url": "https://news.google.com/rss/search?q=public%20health&hl=en-US&gl=US&ceid=US:en"},
    # -- culture / science / sports ------------------------------------------
    # Added 2026-10-04: wider network coverage.
    {"id": "espn", "outlet": "ESPN", "lean": "sports",
     "beat": "sports",
     "url": "https://www.espn.com/espn/rss/news"},
    {"id": "sciencedaily", "outlet": "ScienceDaily", "lean": "science",
     "beat": "science",
     "url": "https://www.sciencedaily.com/rss/all.xml"},
    {"id": "variety", "outlet": "Variety", "lean": "entertainment",
     "beat": "entertainment",
     "url": "https://variety.com/feed/"},
    # -- Denver / local (Herb is in Denver) --------------------------------
    {"id": "cosun", "outlet": "Colorado Sun", "lean": "center / nonprofit local",
     "beat": "colorado",
     "url": "https://coloradosun.com/feed/"},
    {"id": "denverite", "outlet": "Denverite", "lean": "local",
     "beat": "denver",
     "url": "https://denverite.com/feed/"},
    {"id": "9news", "outlet": "9News Denver", "lean": "local",
     "beat": "denver/colorado",
     "url": "https://www.9news.com/feeds/syndication/rss/news/local"},
    {"id": "cpr", "outlet": "Colorado Public Radio", "lean": "center / public",
     "beat": "colorado",
     "url": "https://www.cpr.org/feed/"},
    # -- TechTalk column: tech & innovation ---------------------------------
    # Verified live 2026-09-28 (fetched, parsed, items present).
    {"id": "techcrunch", "outlet": "TechCrunch", "lean": "tech / startups",
     "beat": "topic: tech & innovation",
     "url": "https://techcrunch.com/feed/"},
    {"id": "theverge", "outlet": "The Verge", "lean": "tech / consumer",
     "beat": "topic: tech & innovation",
     "url": "https://www.theverge.com/rss/index.xml"},
    {"id": "arstechnica", "outlet": "Ars Technica", "lean": "tech / deep-dive",
     "beat": "topic: tech & innovation",
     "url": "https://feeds.arstechnica.com/arstechnica/index"},
    {"id": "wired", "outlet": "Wired", "lean": "tech / culture",
     "beat": "topic: tech & innovation",
     "url": "https://www.wired.com/feed/rss"},
    # -- Business column: IPOs & financial markets ---------------------------
    # Verified live 2026-09-28. Google News item-level <source> names the
    # real outlet; ingest.py prefers it over this feed-level label.
    {"id": "gnews-ipo", "outlet": "Google News", "lean": "aggregator / multi-outlet",
     "beat": "topic: ipos",
     "url": "https://news.google.com/rss/search?q=IPO&hl=en-US&gl=US&ceid=US:en"},
    {"id": "gnews-markets", "outlet": "Google News", "lean": "aggregator / multi-outlet",
     "beat": "topic: stock market",
     "url": "https://news.google.com/rss/search?q=stock%20market&hl=en-US&gl=US&ceid=US:en"},
    {"id": "marketwatch", "outlet": "MarketWatch", "lean": "center / business",
     "beat": "markets",
     "url": "https://feeds.marketwatch.com/marketwatch/topstories/"},
    {"id": "cnbc", "outlet": "CNBC", "lean": "center / business",
     "beat": "business",
     "url": "https://www.cnbc.com/id/100003114/device/rss/rss.html"},
]

# Feeds that were checked and could NOT be used, with the reason.
# Documented so nobody "fixes" them back in without re-verifying.
BLOCKED_SOURCES: List[Dict[str, str]] = [
    {"outlet": "Associated Press",
     "url": "https://apnews.com/rss",
     "reason": "HTTP 403 to automated fetches (bot-blocking) as of 2026-09-27."},
    {"outlet": "Denver Post",
     "url": "https://www.denverpost.com/feed/",
     "reason": "HTTP 403 to automated fetches (bot-blocking) as of 2026-09-27."},
    {"outlet": "Reuters",
     "url": "https://www.reuters.com/rssfeed/worldNews",
     "reason": "HTTP 401/404 to automated fetches (bot-blocking) as of 2026-09-27."},
    {"outlet": "Politico",
     "url": "https://www.politico.com/rss/politicopicks.xml",
     "reason": "HTTP 403 to automated fetches (bot-blocking) as of 2026-09-27."},
    {"outlet": "USA Today",
     "url": "https://www.usatoday.com/rss/news/",
     "reason": "No usable RSS endpoint found as of 2026-09-27 (404 / zero items)."},
    {"outlet": "RealClearPolitics",
     "url": "https://www.realclearpolitics.com/rss/",
     "reason": "HTTP 403 to automated fetches (bot-blocking) as of 2026-10-04."},
    {"outlet": "Military.com",
     "url": "https://www.military.com/rss-feeds/news",
     "reason": "No usable RSS endpoint found as of 2026-10-04 (404 on all tried paths)."},
    {"outlet": "Stars and Stripes",
     "url": "https://www.stripes.com/rss",
     "reason": "No usable RSS endpoint found as of 2026-10-04 (404 on all tried paths)."},
]


def all_sources() -> List[Dict[str, str]]:
    """The usable, verified source list."""
    return list(SOURCES)
